# This name will appear in the "Actions" tab of your GitHub repository.
name: QuantConnect Auto Login

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 8,20 * * *'

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # --- THIS STEP IS THE FIX ---
      # It runs two 'pip install' commands to get both playwright and the stealth plugin.
      - name: Install Python Dependencies
        run: |
          pip install playwright
          pip install playwright-stealth

      - name: Install Playwright browsers
        run: python -m playwright install --with-deps

      - name: Run QuantConnect Login Script
        id: login_step
        continue-on-error: true
        env:
          QC_EMAIL: ${{ secrets.QC_EMAIL }}
          QC_PASSWORD: ${{ secrets.QC_PASSWORD }}
        run: python quantconnect_login.py

      - name: Upload Login Failure Screenshot
        if: steps.login_step.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: login-failure-screenshot
          path: login_failure_screenshot.png
          retention-days: 5

      - name: Check script outcome
        if: steps.login_step.outcome == 'failure'
        run: exit 1
