# This name will appear in the "Actions" tab of your GitHub repository.
name: QuantConnect Auto Login

on:
  workflow_dispatch:
  # The schedule is currently commented out. 
  # Uncomment the following lines to enable automatic daily runs.
  # schedule:
  #   - cron: '0 8,20 * * *'

# --- Job Definition ---
jobs:
  # A single job in this workflow, named "login".
  login:
    # The type of runner that the job will run on. Ubuntu is a standard choice.
    runs-on: ubuntu-latest

    steps:
      # --- Step 1: Check out your repository code ---
      # This action checks-out your repository under $GITHUB_WORKSPACE,
      # so your job can access your quantconnect_login.py script.
      - name: Check out repository
        uses: actions/checkout@v4

      # --- Step 2: Set up Python environment ---
      # This action sets up a Python 3.9 environment for us to use.
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # --- Step 3: Install Python dependencies ---
      # We install Playwright, the library our script uses for browser automation.
      - name: Install Playwright
        run: pip install playwright

      # --- Step 4: Install browser binaries ---
      # Playwright needs the actual browser binaries (like Chromium) to work.
      # This command downloads and installs them inside the runner environment.
      - name: Install Playwright browsers
        run: python -m playwright install --with-deps

      # --- Step 5: Execute the login script ---
      # This is the core step. It runs our Python script.
      # 'continue-on-error: true' allows the workflow to proceed to the
      # upload step even if the python script fails (exits with code 1).
      - name: Run QuantConnect Login Script
        id: login_step
        continue-on-error: true
        env:
          # This is where we securely pass the GitHub secrets
          # as environment variables to our Python script.
          QC_EMAIL: ${{ secrets.QC_EMAIL }}
          QC_PASSWORD: ${{ secrets.QC_PASSWORD }}
        run: python quantconnect_login.py

      # --- Step 6: Upload Login Failure Screenshot (NEW) ---
      # This step will only run if the previous step (our script) failed.
      - name: Upload Login Failure Screenshot
        if: steps.login_step.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: login-failure-screenshot
          # The path to the file that the python script creates on failure.
          path: login_failure_screenshot.png
          retention-days: 5 # Keeps the artifact for 5 days

      # --- Step 7: Check script outcome ---
      # This final step ensures the entire job is marked as failed in the UI
      # if our script did not succeed.
      - name: Check script outcome
        if: steps.login_step.outcome == 'failure'
        run: exit 1
